### PR TITLE
Unicode encrypting

### PR DESCRIPTION
**Pull request by AzhurniyBaklan**
It appears that bundle_ru.properties doesn't work if it's not encrypted in unicode beforehand. After doing that, however, the thing works.

### CODE REVIEW

**Comment by genNAowl** [comment]
Hmm. Are you sure that it doesn't work without encrypted? I've never seen any other mods do this; Anyways, I'm off to a weeklong overnight camp in an hour or so; I'll come back to this when I have time.

**Comment by Anuken** [comment]
yikes

**Comment by AzhurniyBaklan** [comment]
> Hmm. Are you sure that it doesn't work without encrypted? I've never seen any other mods do this; Anyways, I'm off to a weeklong overnight camp in an hour or so; I'll come back to this when I have time.
Yep, I am pretty sure it's the reason. Betamindy uses that, and it works. Don't have any idea why it is that way.

**Comment by Anuken** [comment]
> JSON/JS mods don't require that crutch at all and that's quite weird

My guess is that Gradle's encoding options are not properly set to UTF-8. This issue seems very much system encoding dependent, as I have had no problems loading plain Russian bundles from Java mods.

**Pull request merged**
